on:
  release:
    types: [created]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)
  APP_NAME: 'ChatApp'
  EMAIL: 'nate@newsproutsmedia.com'
  TEST_EMAIL: 'newsproutsmedia@gmail.com'
  REFRESH_TOKEN: '1//04Hh7Pmxd_rS6CgYIARAAGAQSNwF-L9IrGcs9G2jno4YOt0VHnvt3ljpGCsPUg0t5dwacRllx-Tn9m3Q8f7BYrR5eCk-q0j_3cQ4'
  CLIENT_SECRET: 'axyZlbcEuKJXywREDyGaUpqS'
  CLIENT_ID: '32845731290-nnf2al9hbh1p13od2iqfktdpdm7e3usp.apps.googleusercontent.com'
  SCHEME: 'http'
  DOMAIN: 'chatapp.newsproutsmedia.com'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'newsproutschatapp'
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2daa4849ae3e45cfa62b4be3fd319547 }}
